In [1]:
import numpy as np

In [7]:
np.zeros((2, 3))       # 2x3 array of zeros
np.ones((3, 2))        # 3x2 array of ones
np.full((2, 2), 7)     # 2x2 array filled with 7
np.eye(3)              # 3x3 Identity matrix
np.linspace(0, 10, 5, dtype=int)   # 5 evenly spaced numbers from 0 to 1
np.arange(0, 10, 2, dtype = float)    # array([0, 2, 4, 6, 8])

array([0., 2., 4., 6., 8.])

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a[1, 2])         # 6
print(a[:, 1])         # column 1 → [2 5]
print(a[1, :])         # row 1 → [4 5 6]
print(a[0:2, 1:3])     # slicing

6
[2 5]
[4 5 6]
[[2 3]
 [5 6]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)      # (2, 3)
print(arr.ndim)       # 2
print(arr.dtype)      # int64
print(arr.size)       # 6
print(arr.itemsize)   # size of each element in bytes

In [26]:
a = np.array([[1, 2, 3], [4,5,6], [7,8,0]])
b = np.array([[0,2,1],[6,5,4],[9,8,7]])
da = np.linalg.det(a)
db = np.linalg.det(b)
print("Determinant of a -- ", da)
print("Determinant of b -- ", db)
inva = np.linalg.inv(a)
invb = np.linalg.inv(b)
eval, evec = np.linalg.eig(a)
print(f"Eigen Value - {eval}\nEigen Vector\n{evec}")

Determinant of a --  27.0
Determinant of b --  -9.000000000000002
Eigen Value - [12.12289378 -0.38838384 -5.73450994]
Eigen Vector
[[-0.29982463 -0.74706733 -0.27625411]
 [-0.70747178  0.65820192 -0.38842554]
 [-0.63999131 -0.09306254  0.87909571]]


In [33]:
# multiplication
a = np.array([[1, 2, 3], [4,5,6], [7,8,0]])
b = np.array([[0,2,1],[6,5,4],[9,8,7]])

# dot product gives scaler value
print(f"dot product\n{np.dot(a,b)}")

# gives prodect
print(f"product\n{np.outer(a,b)}")

dot product
[[39 36 30]
 [84 81 66]
 [48 54 39]]
product
[[ 0  2  1  6  5  4  9  8  7]
 [ 0  4  2 12 10  8 18 16 14]
 [ 0  6  3 18 15 12 27 24 21]
 [ 0  8  4 24 20 16 36 32 28]
 [ 0 10  5 30 25 20 45 40 35]
 [ 0 12  6 36 30 24 54 48 42]
 [ 0 14  7 42 35 28 63 56 49]
 [ 0 16  8 48 40 32 72 64 56]
 [ 0  0  0  0  0  0  0  0  0]]


In [36]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5])

result = np.outer(b,a )
print(result)


[[ 4  8 12]
 [ 5 10 15]]


In [30]:
np.unique(a)          # Get unique values
np.sort(a)            # Sort array
np.where(a > 2)       # Indices where condition is met
np.clip(a, 0, 7)     # Limit values in array
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])